###
POST http://localhost:8000/medicineIncomplete HTTP/1.1
Content-Type: application/json

{
    "id": "111",
    "name": "Ibuprofeno",
    "description": "",
    "category": "String",
    "quantity": "1",
    "price": "String",
    "elabDate": "String",
    "expDate": "String"
}

###

GET http://localhost:8000/all HTTP/1.1

###

GET http://localhost:9000/api/students/12345 HTTP/1.1
###

PUT http://localhost:8000/12345 HTTP/1.1
Content-Type: application/json

{
    "name": "String",
    "description": "String1",
    "category": "String",
    "quantity": "1",
    "price": "String",
    "elabDate": "String",
    "expDate": "String"
}

###

PUT http://localhost:8000/name/Ibuprofeno HTTP/1.1
Content-Type: application/json

{
    "id": "111",
    "quantity": "2",
    "description": "descripcion",
    "name": "Ibuprofeno1",
    "price": "String",
    "elabDate": "String",
    "expDate": "String"
}

###
DELETE http://localhost:8000/111 HTTP/1.1

